import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ASCIEE",
  description: "Generated by create next app",
  icons: {
    icon: "/public/asciee.jpg"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} scroll-smooth antialiased bg-gradient-to-br from-[#581C87] via-[#7C2D92] to-[#4C1D95] animate-aurora-diagonal`}
        
      >
        {children}
      </body>
    </html>
  );
}
